project:
  type: website
  output-dir: docs

website:
  title: "Rachid Sahli"
  description: "Site personnel de Rachid Sahli"
  
  repo-url: https://github.com/rachidsahli/Site-personnel
  
  navbar: 
    background: warning
    foreground: light
    
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: À propos
      - href: projets.qmd
        text: Projets
      - href: blog.qmd
        text: Blog
        
    right: 
      - icon: github
        href: https://github.com/rachidsahli
      - icon: envelope
        href: mailto:sahlirachid427@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/rachidsahli/
      - icon: file-person
        text: CV
        href: https://github.com/rachidsahli
        
  page-footer: "Copyright 2025, Rachid SAHLI"

format:
  html:
    theme: 
          light: Default
          dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

