project:
  type: website
  output-dir: docs

website:
  title: "Rachid Sahli"
  navbar: 
    background: warning
    foreground: light
    
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: À propos
      - href: projets.qmd
        text: Projets
      - href: blog.qmd
        text: Blog
        
  page-footer: "Copyright 2025, Rachid SAHLI"

format:
  html:
    theme: 
          light: Default
          dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

